# Dify API Server Start
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  labels:
    app: api
  namespace: dify
spec:
  replicas: 1
  minReadySeconds: 10
  serviceName: api
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: langgenius/dify-api:0.15.2
        env:
          - name: MODE
            value: "api"
          - name: REDIS_PORT
            value: "6379"
          - name: DB_PORT
            value: "5432"
        envFrom:
          - configMapRef:
              name: api-configmap
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        ports:
        - containerPort: 5001
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: api-pvc
          mountPath: /app/api/storage
  volumeClaimTemplates:
  - metadata:
      name: api-pvc
    spec:
      accessModes:
        - ReadWriteOnce  
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2-encrypted
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: dify
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP


