apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: dify
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6-alpine
        command: ["redis-server", "--requirepass", "difyai123456"]
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 102Mi
        env:
          - name: REDIS_PASSWORD
            value: "difyai123456"
          - name: REDISCLI_AUTH
            value: "difyai123456"
        ports:
        - containerPort: 6379
        readinessProbe:
          exec:
            command:
              - "redis-cli"
              - "ping"
              - "-a"
              - "difyai123456"
        volumeMounts:
        - name: redis-pvc
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes:
        - ReadWriteOnce  
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2-encrypted

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dify
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
